[package]
name = "docker-bell"
authors = ["Sven Willner <sven.willner@gmail.com>"]
version = "0.2.0"
edition = "2024"
license = "MIT"

[dependencies]
axum = "0.8"
clap = { version = "4", features = ["derive"] }
docker-api = "0.14"
futures-util = "0.3"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "net", "process", "rt-multi-thread", "time"] }
tower-http = { version = "0.7", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
